const ZONES = ["ATA", "MED", "DEF"];
const LANES = ["Izquierda", "Centro", "Derecha"];
const GOAL_DISTANCE = 10;
const initialTeams = [
  {id:"a",name:"Verdes",color:"#62dc86",keeper:82,players:[{name:"L. Silva",natural:"DL",attack:89,midfield:69,defense:34,zone:null},{name:"M. Costa",natural:"MD",attack:75,midfield:86,defense:68,zone:null},{name:"T. Núñez",natural:"DF",attack:44,midfield:65,defense:88,zone:null},{name:"R. Lima",natural:"MD",attack:78,midfield:80,defense:61,zone:null}]},
  {id:"b",name:"Naranjas",color:"#ff914d",keeper:79,players:[{name:"J. Pereira",natural:"DL",attack:86,midfield:65,defense:29,zone:null},{name:"A. Gómez",natural:"MD",attack:72,midfield:83,defense:66,zone:null},{name:"F. Soto",natural:"DF",attack:38,midfield:61,defense:90,zone:null},{name:"B. Torres",natural:"DL",attack:84,midfield:71,defense:39,zone:null}]}
];
let state;
const clone=v=>JSON.parse(JSON.stringify(v));
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
function reset(){state={teams:clone(initialTeams),selected:[null,null],started:false,finished:false,goals:[0,0],distance:[0,0],attacker:0,phase:"attack",attackLane:null,turn:1,events:[],lastOutcome:null};render();}
function allPlaced(){return state.teams.every(team=>team.players.every(player=>player.zone));}
function baseRating(team){return(team.players.reduce((n,p)=>n+Math.max(p.attack,p.midfield,p.defense),0)+team.keeper)/5;}
function advantageBonuses(){const r=state.teams.map(baseRating),d=Math.abs(r[0]-r[1]),b=d<=1?0:d<=3?3:d<=4.5?5:7;return r[0]>=r[1]?[b,0]:[0,b];}
function teamPower(team,index){const g=Object.fromEntries(ZONES.map(z=>[z,team.players.filter(p=>p.zone===z)]));const line=(z,k)=>g[z].length?g[z].reduce((n,p)=>n+p[k],0)/4:5;const mid=line("MED","midfield"),bonus=advantageBonuses()[index];return{attack:Math.round(line("ATA","attack")+mid*.3+bonus),midfield:Math.round(mid),defense:Math.round(line("DEF","defense")+mid*.3+team.keeper*.15+bonus),bonus,formation:`${g.DEF.length}-${g.MED.length}-${g.ATA.length}`,empty:ZONES.filter(z=>!g[z].length)};}
function laneDuel(attacker,defender){const a=teamPower(state.teams[attacker],attacker),d=teamPower(state.teams[defender],defender);return{blockChance:Math.round(clamp(58+(d.defense-a.attack)*.75,18,92)),advances:Math.round(clamp(2+(a.attack-d.defense)/22,1,5))};}
function selectPlayer(t,p){if(state.started)return;state.selected[t]=p;render();}
function placeSelected(t,z){if(state.started||state.selected[t]===null)return;state.teams[t].players[state.selected[t]].zone=z;state.selected[t]=null;render();}
function renderTeam(team,index){const p=teamPower(team,index),selected=state.selected[index],placed=team.players.filter(x=>x.zone).length;return `<article class="team-card" style="--team:${team.color}"><div class="team-head"><div class="team-title"><span class="team-dot"></span><h3>${team.name}</h3></div><span class="formation">${placed? p.formation:"Cancha vacía"}</span></div><div class="players">${team.players.map((x,i)=>`<div class="player ${selected===i?"selected":""} ${x.zone?"placed":"unplaced"}" data-select-player="${index}-${i}" role="button" tabindex="0"><div class="player-top"><div><div class="player-name">${x.name}</div><div class="natural">Perfil: ${x.natural} · ${x.zone?`ubicado en ${x.zone}`:"sin ubicar"}</div>${selected===i?'<div class="selected-hint">Ahora tocá la línea donde querés colocarlo</div>':''}</div><div class="stats"><span class="stat"><b>${x.defense}</b><small>DEF</small></span><span class="stat"><b>${x.midfield}</b><small>MED</small></span><span class="stat"><b>${x.attack}</b><small>ATA</small></span></div></div></div>`).join("")}</div><div class="formation-pitch">${ZONES.map(z=>`<button type="button" class="formation-zone ${selected!==null?"ready":""}" data-place="${index}-${z}" ${state.started?"disabled":""}><span class="zone-label">${({DEF:"DEFENSA",MED:"MEDIO",ATA:"ATAQUE"})[z]}</span>${team.players.filter(x=>x.zone===z).map(x=>`<span class="pitch-player">${x.name}</span>`).join("")}</button>`).join("")}</div><p class="placement-count">${placed}/4 jugadores ubicados · formación ${p.formation}</p>${placed===4&&p.empty.length?`<p class="warning">⚠ Línea casi anulada: ${p.empty.map(z=>({DEF:"defensa",MED:"medio",ATA:"ataque"})[z]).join(", ")}.</p>`:""}<div class="power-grid"><div class="power"><strong>${p.attack}</strong><small>Ataque</small></div><div class="power"><strong>${p.midfield}</strong><small>Medio</small></div><div class="power"><strong>${p.defense}</strong><small>Defensa</small></div><div class="power"><strong>+${p.bonus}</strong><small>Ventaja</small></div></div></article>`;}
function renderDuels(){const p=state.teams.map(teamPower),rows=[["Ataque verde",p[0].attack,p[1].defense,"Defensa naranja"],["Ataque naranja",p[1].attack,p[0].defense,"Defensa verde"],["Mediocampo",p[0].midfield,p[1].midfield,"Control central"]];return rows.map(([label,a,b,sub])=>{const t=Math.max(1,a+b);return `<div class="duel"><div class="duel-label"><b>${label}</b><small>${sub}</small></div><div class="meter"><span class="meter-a" style="width:${a/t*100}%"></span><span class="meter-b" style="width:${b/t*100}%"></span></div><div class="duel-score">${a}:${b}</div></div>`}).join("");}
function renderOdds(){return state.teams.map((t,i)=>{const d=laneDuel(i,1-i);return `<div class="odds-card" style="--team:${t.color}"><div><span>Avance si supera la defensa</span><strong>${d.advances}</strong></div><p>${teamPower(t,i).formation} · calidad ${baseRating(t).toFixed(1)} · ventaja +${teamPower(t,i).bonus}</p></div>`}).join("");}
function instruction(){if(!state.started)return allPlaced()?"Los dos equipos están listos. Ya podés comenzar el partido.":"Tocá un jugador y después la línea donde querés colocarlo.";if(state.finished)return resultText();const a=state.teams[state.attacker],d=state.teams[1-state.attacker];if(state.phase==="attack")return`${a.name} ataca: elegí un carril.`;if(state.phase==="handoff")return`Ataque guardado. Pasale el dispositivo a ${d.name}.`;if(state.phase==="result")return state.lastOutcome.title;return`${d.name} defiende: intentá adivinar el carril del ataque.`;}
function renderLanePicker(){if(!state.started||state.finished)return"";if(state.phase==="handoff")return`<div class="match-pitch obscured"><div class="handoff"><b>La jugada quedó oculta</b><span>${state.teams[1-state.attacker].name} debe elegir la defensa sin verla.</span><button class="primary" id="defendReady" type="button">Defender</button></div></div>`;if(state.phase==="result")return`<div class="match-pitch result-pitch"><div class="outcome ${state.lastOutcome.type}"><strong>${state.lastOutcome.title}</strong><span>${state.lastOutcome.detail}</span><button class="primary" id="nextTurn" type="button">Siguiente turno</button></div></div>`;return `<div class="match-pitch ${state.phase}">${LANES.map((l,i)=>`<button type="button" class="lane-button" data-lane="${i}"><span>${l}</span><i class="pitch-lines"></i>${state.phase==="attack"&&i===1?`<em class="ball" style="bottom:${14+state.distance[state.attacker]/GOAL_DISTANCE*155}px">●</em>`:""}</button>`).join("")}</div>`;}
function renderProgress(){return state.teams.map((t,i)=>`<div class="attack-progress" style="--team:${t.color}"><div><span>Avance de ${t.name}</span><b>${state.distance[i]}/${GOAL_DISTANCE}</b></div><div class="progress-track"><div class="progress-fill" style="width:${state.distance[i]/GOAL_DISTANCE*100}%"></div></div></div>`).join("");}
function chooseLane(lane){if(state.phase==="attack"){state.attackLane=lane;state.phase="handoff";render();return;}if(state.phase==="defense")resolveDuel(lane);}
function resolveDuel(defenseLane){const a=state.attacker,d=1-a,duel=laneDuel(a,d),same=state.attackLane===defenseLane,blocked=same&&Math.random()*100<duel.blockChance;let title,type,detail;if(blocked){title="¡RECUPERACIÓN!";type="recovery";detail=`${state.teams[d].name} cubrió ${LANES[defenseLane].toLowerCase()}.`;state.attacker=d;}else{state.distance[a]+=duel.advances;if(state.distance[a]>=GOAL_DISTANCE){state.goals[a]++;state.distance[a]=0;title="¡GOL!";type="goal";detail=`Gol de ${state.teams[a].name}.`;state.attacker=d;}else{title=`¡AVANCE DE ${duel.advances}!`;type="advance";detail=`${state.teams[a].name} sigue acercándose al arco.`;}}const lanes=`Ataque: ${LANES[state.attackLane]}. Defensa: ${LANES[defenseLane]}.`;state.lastOutcome={title,type,detail:`${detail} ${lanes}`};state.events.unshift({color:state.teams[a].color,title,detail:` ${detail} ${lanes}`});state.phase="result";render();}
function nextTurn(){state.turn++;state.attackLane=null;state.lastOutcome=null;if(state.goals.some(g=>g>=3)||state.turn>30)state.finished=true;else state.phase="attack";render();}
function resultText(){if(state.goals[0]===state.goals[1])return"Partido terminado en empate";return`Ganó ${state.teams[state.goals[0]>state.goals[1]?0:1].name}`;}
function startOrReset(){if(state.finished){reset();return;}if(!allPlaced())return;state.started=true;state.selected=[null,null];render();}
function render(){document.querySelector("#teams").innerHTML=state.teams.map(renderTeam).join("");document.querySelector("#duels").innerHTML=renderDuels();document.querySelector("#odds").innerHTML=renderOdds();document.querySelector("#scoreA").textContent=state.goals[0];document.querySelector("#scoreB").textContent=state.goals[1];document.querySelector("#roundLabel").textContent=state.finished?"Final":state.started?`Turno ${state.turn}`:"Preparación";document.querySelector("#statusText").textContent=state.finished?resultText():state.started?`${state.teams[state.attacker].name} tiene la posesión`:allPlaced()?"Tácticas listas":"Armá ambos equipos";const play=document.querySelector("#playBtn");play.textContent=state.finished?"Jugar revancha":state.started?"Partido en curso":allPlaced()?"Comenzar partido":"Ubicá los 8 jugadores";play.disabled=(state.started&&!state.finished)||(!state.started&&!allPlaced());document.querySelector("#commentary").innerHTML=`<p>${instruction()}</p>`;document.querySelector("#lanePicker").innerHTML=renderLanePicker();document.querySelector("#progressWrap").innerHTML=renderProgress();document.querySelector("#eventLog").innerHTML=state.events.slice(0,10).map(e=>`<div class="event" style="--team:${e.color}"><b>${e.title}</b>${e.detail}</div>`).join("");bind();}
function bind(){document.querySelectorAll("[data-select-player]").forEach(el=>{const go=()=>{const[t,p]=el.dataset.selectPlayer.split("-").map(Number);selectPlayer(t,p)};el.addEventListener("click",go);el.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();go()}})});document.querySelectorAll("[data-place]").forEach(el=>el.addEventListener("click",()=>{const[t,z]=el.dataset.place.split("-");placeSelected(Number(t),z)}));document.querySelectorAll("[data-lane]").forEach(el=>el.addEventListener("click",()=>chooseLane(Number(el.dataset.lane))));document.querySelector("#defendReady")?.addEventListener("click",()=>{state.phase="defense";render()});document.querySelector("#nextTurn")?.addEventListener("click",nextTurn);}
document.querySelector("#playBtn").addEventListener("click",startOrReset);
document.querySelector("#resetBtn").addEventListener("click",reset);
reset();
